server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/Market-app-Fer
spring.datasource.username=postgres
spring.datasource.password=Datos845

spring.datasource.driver-class-name=org.postgresql.Driver