package mx.edu.tecdesotware.Market_Backend_Demo.web.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import mx.edu.tecdesotware.Market_Backend_Demo.domain.Purchase;
import mx.edu.tecdesotware.Market_Backend_Demo.domain.service.PurchaseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/purchases")
@Tag(name = "Purchase", description = "Manage purchases and their line items in the store")
public class PurchaseController {

    @Autowired
    private PurchaseService purchaseService;

    @Operation(summary = "Get All Purchases", description = "Return a list of all registered purchases")
    @ApiResponse(responseCode = "200", description = "Successful retrieval of purchases")
    @ApiResponse(responseCode = "500", description = "Internal Server Error")
    @GetMapping("/all")
    public ResponseEntity<List<Purchase>> getAll() {
        return new ResponseEntity<>(purchaseService.getAll(), HttpStatus.OK);
    }

    @Operation(summary = "Get Purchases By Client", description = "Return all purchases made by a specific client")
    @ApiResponse(responseCode = "200", description = "Purchases found for the client")
    @ApiResponse(responseCode = "404", description = "No purchases found for the client")
    @ApiResponse(responseCode = "500", description = "Internal Server Error")
    @GetMapping("/client/{idClient}")
    public ResponseEntity<List<Purchase>> getByClient(
            @Parameter(description = "ID of the client parameter", example = "4546221", required = true)
            @PathVariable("idClient") String clientId) {
        return purchaseService.getByClient(clientId)
                .map(purchases -> new ResponseEntity<>(purchases, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    @Operation(
            summary = "Save New Purchase",
            description = "Register a new purchase with its line items and return the created purchase. "
                    + "Do not send 'purchaseId': the id is generated by the database. "
                    + "'clientId' must be an existing client and each 'productId' an existing product, "
                    + "otherwise the database rejects the insert with a foreign key error.",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    required = true,
                    content = @Content(
                            examples = @ExampleObject(
                                    name = "Example Purchase",
                                    value = """
                                            {
                                                "clientId": "4546221",
                                                "date": "2026-07-16T10:30:00",
                                                "paymentMethod": "E",
                                                "comment": "Compra de contado",
                                                "state": "P",
                                                "items": [
                                                    {
                                                        "productId": 1,
                                                        "quantity": 3,
                                                        "total": 60,
                                                        "active": true
                                                    },
                                                    {
                                                        "productId": 3,
                                                        "quantity": 1,
                                                        "total": 20,
                                                        "active": true
                                                    }
                                                ]
                                            }
                                            """
                            )
                    )
            )
    )
    @ApiResponse(responseCode = "201", description = "Purchase created successfully")
    @ApiResponse(responseCode = "400", description = "Invalid purchase data")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @ApiResponse(responseCode = "403", description = "Forbidden")
    @ApiResponse(responseCode = "409", description = "Purchase conflict (duplicate purchase)")
    @ApiResponse(responseCode = "500", description = "Internal server error")
    @PostMapping("/save")
    public ResponseEntity<Purchase> save(@RequestBody Purchase purchase) {
        return new ResponseEntity<>(purchaseService.save(purchase), HttpStatus.CREATED);
    }
}
